using System.Reflection;
using System.Runtime.InteropServices;
[assembly: ComVisible(false)]
[assembly: Guid("0f95518f-008d-486d-a827-dad050873cd6")]
[assembly: AssemblyTitle("Octopus AdminBase 1.1.0.r7_052bb10c")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("HTB")]
[assembly: AssemblyProduct("Octopus")]
[assembly: AssemblyCopyright("Copyright © HTB 2013")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.1.0.7")]
[assembly: AssemblyInformationalVersion("1.1.0.7")]
