using System.Reflection;
using System.Runtime.InteropServices;
[assembly: ComVisible(false)]
[assembly: Guid("ab838eaf-1949-415d-a2b5-064cfefabe5e")]
[assembly: AssemblyTitle("Octopus Esb 1.1.0.r0_")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("HTB")]
[assembly: AssemblyProduct("Octopus")]
[assembly: AssemblyCopyright("Copyright © HTB 2011")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("1.1.0.0")]
