using System.Reflection;
using System.Runtime.InteropServices;
[assembly: ComVisible(false)]
[assembly: Guid("10dfb98b-8bc9-4286-9995-569f1187bd33")]
[assembly: AssemblyTitle("Octopus Base 1.1.0.r0_")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("HTB")]
[assembly: AssemblyProduct("Octopus")]
[assembly: AssemblyCopyright("Copyright © HTB 2012")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("1.1.0.0")]
