using System.Reflection;
using System.Runtime.InteropServices;
[assembly: ComVisible(false)]
[assembly: Guid("bc9420d6-42ed-4498-95dd-182866cfa821")]
[assembly: AssemblyTitle("Octopus Runtime 1.1.0.r0_")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("HTB")]
[assembly: AssemblyProduct("Octopus")]
[assembly: AssemblyCopyright("Copyright © HTB 2011")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("1.1.0.0")]
