using System.Reflection;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("Octopus.SecurityPermissions 1.1.0.r7_052bb10c")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("HTB")]
[assembly: AssemblyProduct("Octopus")]
[assembly: AssemblyCopyright("Copyright © HTB 2012")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("4b3667b0-926e-4e87-929c-b68d85366dd0")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.1.0.7")]
[assembly: AssemblyInformationalVersion("1.1.0.7")]
